
export interface CommonRoot {
  root: string;
  meaning: string;
}

export const COMMON_ROOTS: CommonRoot[] = [
  { root: "acri/acer", meaning: "sharp, bitter" },
  { root: "act/ag", meaning: "to do, to drive" },
  { root: "aer", meaning: "air" },
  { root: "ali", meaning: "other" },
  { root: "alter", meaning: "change" },
  { root: "am/ami", meaning: "love, friend" },
  { root: "ambul", meaning: "walk" },
  { root: "anim", meaning: "life, spirit" },
  { root: "ann/enn", meaning: "year" },
  { root: "ante", meaning: "before" },
  { root: "anthro", meaning: "human" },
  { root: "anti", meaning: "against" },
  { root: "aqua", meaning: "water" },
  { root: "arch", meaning: "ruler, chief, ancient" },
  { root: "art", meaning: "skill" },
  { root: "aster/astr", meaning: "star" },
  { root: "aud", meaning: "hear" },
  { root: "auto", meaning: "self" },
  { root: "bell", meaning: "war" },
  { root: "bene", meaning: "good" },
  { root: "bi/bin", meaning: "two" },
  { root: "bibl", meaning: "book" },
  { root: "bio", meaning: "life" },
  { root: "brev", meaning: "short" },
  { root: "cad/cas", meaning: "fall" },
  { root: "cand", meaning: "white, glowing" },
  { root: "cant", meaning: "sing" },
  { root: "cap/cip/cept", meaning: "take, hold" },
  { root: "capit", meaning: "head" },
  { root: "carn", meaning: "flesh" },
  { root: "ced/cess", meaning: "yield, go" },
  { root: "cent", meaning: "hundred" },
  { root: "centr", meaning: "center" },
  { root: "cern/cert", meaning: "separate, sure" },
  { root: "chrom", meaning: "color" },
  { root: "chron", meaning: "time" },
  { root: "cid/cis", meaning: "cut, kill" },
  { root: "circum", meaning: "around" },
  { root: "clam/claim", meaning: "shout" },
  { root: "clar", meaning: "clear" },
  { root: "clin", meaning: "lean, bend" },
  { root: "clud/clus", meaning: "close" },
  { root: "cogn", meaning: "know" },
  { root: "contra/counter", meaning: "against" },
  { root: "cord", meaning: "heart" },
  { root: "corp", meaning: "body" },
  { root: "cosm", meaning: "universe" },
  { root: "crat/cracy", meaning: "rule" },
  { root: "cre/cresc", meaning: "grow" },
  { root: "cred", meaning: "believe" },
  { root: "crypt", meaning: "hidden" },
  { root: "culp", meaning: "blame" },
  { root: "curr/curs", meaning: "run" },
  { root: "cycl", meaning: "circle, ring" },
  { root: "de", meaning: "down, away" },
  { root: "dem", meaning: "people" },
  { root: "dent", meaning: "tooth" },
  { root: "derm", meaning: "skin" },
  { root: "dic/dict", meaning: "speak" },
  { root: "dign", meaning: "worthy" },
  { root: "dis/dif", meaning: "not, apart" },
  { root: "doc/doct", meaning: "teach" },
  { root: "dol", meaning: "pain" },
  { root: "domin", meaning: "master" },
  { root: "don", meaning: "give" },
  { root: "dorm", meaning: "sleep" },
  { root: "dox", meaning: "opinion" },
  { root: "duc/duct", meaning: "lead" },
  { root: "dur", meaning: "hard, lasting" },
  { root: "dyn", meaning: "power" },
  { root: "ego", meaning: "self" },
  { root: "endo", meaning: "within" },
  { root: "equ", meaning: "equal" },
  { root: "err", meaning: "wander" },
  { root: "ethno", meaning: "race, culture" },
  { root: "eu", meaning: "good, well" },
  { root: "ex", meaning: "out" },
  { root: "fac/fic/fect", meaning: "make, do" },
  { root: "fall/fals", meaning: "deceive" },
  { root: "fer", meaning: "bear, carry" },
  { root: "fid", meaning: "faith" },
  { root: "fin", meaning: "end" },
  { root: "flect/flex", meaning: "bend" },
  { root: "flu/flux", meaning: "flow" },
  { root: "form", meaning: "shape" },
  { root: "fort", meaning: "strong" },
  { root: "fract/frag", meaning: "break" },
  { root: "fus", meaning: "pour" },
  { root: "gam", meaning: "marriage" },
  { root: "gen", meaning: "birth, race" },
  { root: "geo", meaning: "earth" },
  { root: "gnos", meaning: "know" },
  { root: "grad/gress", meaning: "step" },
  { root: "graph/gram", meaning: "write" },
  { root: "grat", meaning: "pleasing" },
  { root: "grav", meaning: "heavy" },
  { root: "greg", meaning: "flock" },
  { root: "hem/hemo", meaning: "blood" },
  { root: "hetero", meaning: "different" },
  { root: "homo", meaning: "same" },
  { root: "host", meaning: "enemy" },
  { root: "hydr", meaning: "water" },
  { root: "hyper", meaning: "over, above" },
  { root: "hypo", meaning: "under" },
  { root: "imag", meaning: "likeness" },
  { root: "init", meaning: "beginning" },
  { root: "inter", meaning: "between" },
  { root: "intra", meaning: "within" },
  { root: "ject", meaning: "throw" },
  { root: "jud", meaning: "judge" },
  { root: "junct", meaning: "join" },
  { root: "jur/jus", meaning: "law" },
  { root: "lab", meaning: "work" },
  { root: "lat", meaning: "side, wide" },
  { root: "laud", meaning: "praise" },
  { root: "leg/lect", meaning: "choose, read" },
  { root: "lev", meaning: "light, rise" },
  { root: "liber", meaning: "free" },
  { root: "lingu", meaning: "tongue, language" },
  { root: "lith", meaning: "stone" },
  { root: "loc", meaning: "place" },
  { root: "log/loqu", meaning: "speak" },
  { root: "luc/lum", meaning: "light" },
  { root: "macro", meaning: "large" },
  { root: "magn", meaning: "large" },
  { root: "mal", meaning: "bad" },
  { root: "man", meaning: "hand" },
  { root: "mand", meaning: "command" },
  { root: "mar", meaning: "sea" },
  { root: "mater/matr", meaning: "mother" },
  { root: "max", meaning: "greatest" },
  { root: "mem", meaning: "remember" },
  { root: "ment", meaning: "mind" },
  { root: "merg/mers", meaning: "dip" },
  { root: "meta", meaning: "beyond, change" },
  { root: "meter/metr", meaning: "measure" },
  { root: "micro", meaning: "small" },
  { root: "migr", meaning: "move" },
  { root: "min", meaning: "small" },
  { root: "mit/miss", meaning: "send" },
  { root: "mob/mot/mov", meaning: "move" },
  { root: "mon", meaning: "warn" },
  { root: "mono", meaning: "one" },
  { root: "mor/mort", meaning: "death" },
  { root: "morph", meaning: "shape" },
  { root: "multi", meaning: "many" },
  { root: "mut", meaning: "change" },
  { root: "nat", meaning: "born" },
  { root: "nav", meaning: "ship" },
  { root: "neg", meaning: "deny" },
  { root: "neo", meaning: "new" },
  { root: "nom/nym", meaning: "name" },
  { root: "not", meaning: "mark" },
  { root: "nounc/nunc", meaning: "declare" },
  { root: "nov", meaning: "new" },
  { root: "nox/noc", meaning: "night, harm" },
  { root: "numer", meaning: "number" },
  { root: "ob", meaning: "against" },
  { root: "omni", meaning: "all" },
  { root: "onym", meaning: "name" },
  { root: "oper", meaning: "work" },
  { root: "ortho", meaning: "straight" },
  { root: "pac", meaning: "peace" },
  { root: "pan", meaning: "all" },
  { root: "par", meaning: "equal" },
  { root: "para", meaning: "beside" },
  { root: "pater/patr", meaning: "father" },
  { root: "path", meaning: "feeling" },
  { root: "ped/pod", meaning: "foot" },
  { root: "pel/puls", meaning: "drive" },
  { root: "pend/pens", meaning: "hang" },
  { root: "peri", meaning: "around" },
  { root: "phil", meaning: "love" },
  { root: "phon", meaning: "sound" },
  { root: "photo", meaning: "light" },
  { root: "plac", meaning: "please" },
  { root: "plen/plet", meaning: "fill" },
  { root: "poli", meaning: "city" },
  { root: "poly", meaning: "many" },
  { root: "pon/pos", meaning: "place, put" },
  { root: "pop", meaning: "people" },
  { root: "port", meaning: "carry" },
  { root: "pot", meaning: "power" },
  { root: "pre", meaning: "before" },
  { root: "prim", meaning: "first" },
  { root: "pro", meaning: "forward" },
  { root: "proto", meaning: "first" },
  { root: "psych", meaning: "mind" },
  { root: "pug", meaning: "fight" },
  { root: "punct", meaning: "point" },
  { root: "put", meaning: "think" },
  { root: "pyr", meaning: "fire" },
  { root: "quer/quis", meaning: "ask, seek" },
  { root: "radic", meaning: "root" },
  { root: "re", meaning: "back, again" },
  { root: "rect", meaning: "straight" },
  { root: "reg", meaning: "guide, rule" },
  { root: "retro", meaning: "backward" },
  { root: "rid/ris", meaning: "laugh" },
  { root: "rog", meaning: "ask" },
  { root: "rupt", meaning: "break" },
  { root: "sacr/sanct", meaning: "holy" },
  { root: "sci", meaning: "know" },
  { root: "scop", meaning: "see" },
  { root: "scrib/script", meaning: "write" },
  { root: "sect", meaning: "cut" },
  { root: "sed/sid/sess", meaning: "sit" },
  { root: "sem", meaning: "seed, sow" },
  { root: "semi", meaning: "half" },
  { root: "sen", meaning: "old" },
  { root: "sens/sent", meaning: "feel" },
  { root: "sequ/secut", meaning: "follow" },
  { root: "serv", meaning: "save, serve" },
  { root: "sign", meaning: "mark" },
  { root: "simil/simul", meaning: "like" },
  { root: "sol", meaning: "alone" },
  { root: "solv/solut", meaning: "loosen" },
  { root: "somn", meaning: "sleep" },
  { root: "son", meaning: "sound" },
  { root: "soph", meaning: "wise" },
  { root: "spec/spect", meaning: "look" },
  { root: "spir", meaning: "breathe" },
  { root: "stat/stab", meaning: "stand" },
  { root: "strict/string", meaning: "tight" },
  { root: "struct", meaning: "build" },
  { root: "sub", meaning: "under" },
  { root: "sum", meaning: "highest" },
  { root: "super/sur", meaning: "over" },
  { root: "sym/syn", meaning: "together" },
  { root: "tact/tang", meaning: "touch" },
  { root: "techn", meaning: "skill, art" },
  { root: "tele", meaning: "far" },
  { root: "temp", meaning: "time" },
  { root: "ten/tent/tin", meaning: "hold" },
  { root: "term", meaning: "end" },
  { root: "terr", meaning: "land" },
  { root: "test", meaning: "witness" },
  { root: "tex", meaning: "weave" },
  { root: "theo", meaning: "god" },
  { root: "therm", meaning: "heat" },
  { root: "tort", meaning: "twist" },
  { root: "tox", meaning: "poison" },
  { root: "tract", meaning: "pull" },
  { root: "trans", meaning: "across" },
  { root: "trib", meaning: "pay, bestow" },
  { root: "turb", meaning: "agitate" },
  { root: "typ", meaning: "print, model" },
  { root: "ultim", meaning: "last" },
  { root: "ultra", meaning: "beyond" },
  { root: "uni", meaning: "one" },
  { root: "urb", meaning: "city" },
  { root: "vac", meaning: "empty" },
  { root: "val", meaning: "strength, worth" },
  { root: "var", meaning: "vary" },
  { root: "ven/vent", meaning: "come" },
  { root: "ver", meaning: "truth" },
  { root: "verb", meaning: "word" },
  { root: "vers/vert", meaning: "turn" },
  { root: "via", meaning: "way" },
  { root: "vid/vis", meaning: "see" },
  { root: "vinc/vict", meaning: "conquer" },
  { root: "vit/viv", meaning: "live" },
  { root: "voc/vok", meaning: "call" },
  { root: "vol", meaning: "wish" },
  { root: "volv/volu", meaning: "roll" },
  { root: "vor", meaning: "eat" },
  { root: "zo", meaning: "animal" }
];
